/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false`
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env {
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
